=== IgorrG/testsuite/contrib/sipp/sipp.dtd
<!ELEMENT scenario ( CallLengthRepartition | ResponseTimeRepartition | Reference | send | recv | pause | nop | sendCmd | recvCmd | label | timewait)* >
<!ATTLIST scenario name CDATA #IMPLIED >

<!-- BEGIN message commands -->

<!ENTITY % messageCmdCommon '
  start_rtd NMTOKEN #IMPLIED
  rtd NMTOKEN #IMPLIED
  repeat_rtd (true|false) #IMPLIED
  crlf (true|false) #IMPLIED
  next NMTOKEN #IMPLIED
  test NMTOKEN #IMPLIED
  chance NMTOKEN #IMPLIED
  condexec NMTOKEN #IMPLIED
  condexec_inverse NMTOKEN #IMPLIED
  counter NMTOKEN #IMPLIED
  '>

<!ELEMENT send (#PCDATA|action)* >
<!ATTLIST send %messageCmdCommon; >
<!ATTLIST send retrans NMTOKEN #IMPLIED >
<!ATTLIST send lost NMTOKEN #IMPLIED >
<!ATTLIST send start_txn NMTOKEN #IMPLIED >
<!ATTLIST send ack_txn NMTOKEN #IMPLIED >

<!ELEMENT recv ( action? ) >
<!ATTLIST recv %messageCmdCommon; >
<!ATTLIST recv response NMTOKEN #IMPLIED >
<!ATTLIST recv request CDATA #IMPLIED >
<!ATTLIST recv optional (true|false) #IMPLIED >
<!ATTLIST recv ignosesdp (true|false) #IMPLIED >
<!ATTLIST recv rrs (true|false) #IMPLIED >
<!ATTLIST recv auth (true|false) #IMPLIED >
<!ATTLIST recv lost NMTOKEN #IMPLIED >
<!ATTLIST recv timeout NMTOKEN #IMPLIED >
<!ATTLIST recv ontimeout NMTOKEN #IMPLIED >
<!ATTLIST recv regexp_match (true|false) #IMPLIED >
<!ATTLIST recv response_txn NMTOKEN #IMPLIED >

<!ELEMENT pause EMPTY >
<!ATTLIST pause %messageCmdCommon; >
<!ATTLIST pause milliseconds NMTOKEN #IMPLIED >
<!ATTLIST pause variable NMTOKEN #IMPLIED >
<!ATTLIST pause distribution NMTOKEN #IMPLIED >
<!ATTLIST pause sanity_check (true|false) #IMPLIED >

<!ELEMENT nop ( action? ) >
<!ATTLIST nop %messageCmdCommon; >
<!ATTLIST nop display CDATA #IMPLIED >

<!ELEMENT sendCmd ( #PCDATA ) >
<!ATTLIST sendCmd %messageCmdCommon; >
<!ATTLIST sendCmd dest NMTOKEN #IMPLIED >

<!ELEMENT recvCmd ( action? ) >
<!ATTLIST recvCmd %messageCmdCommon; >
<!ATTLIST recvCmd src NMTOKEN #IMPLIED >

<!-- END message commands -->

<!ELEMENT label ( #PCDATA ) >
<!ATTLIST label id NMTOKEN #IMPLIED >

<!ELEMENT ResponseTimeRepartition EMPTY >
<!ATTLIST ResponseTimeRepartition value CDATA #REQUIRED >

<!ELEMENT CallLengthRepartition EMPTY >
<!ATTLIST CallLengthRepartition value CDATA #REQUIRED >

<!ELEMENT action ( add | assign | assignstr | divide | ereg | exec | gettimeofday | insert | jump | log | lookup | multiply | replace | rtp_echo | sample | setdest | strcmp | subtract | test | todouble | urldecode | urlencode | verifyauth | warning )+ >

<!-- BEGIN actions -->

<!ELEMENT ereg EMPTY >
<!ATTLIST ereg assign_to CDATA #REQUIRED >
<!ATTLIST ereg case_indep (true|false) #IMPLIED >
<!ATTLIST ereg check_it (true|false) "false" >
<!ATTLIST ereg check_it_inverse (true|false) "false" >
<!ATTLIST ereg header NMTOKEN #IMPLIED >
<!ATTLIST ereg occurence CDATA #IMPLIED >
<!ATTLIST ereg regexp CDATA #REQUIRED >
<!ATTLIST ereg search_in (msg|hdr) "msg" >
<!ATTLIST ereg start_line (true|false) #IMPLIED >
<!ATTLIST ereg variable CDATA #IMPLIED >


<!ELEMENT log EMPTY >
<!ATTLIST log message CDATA #REQUIRED >

<!ELEMENT warning EMPTY >
<!ATTLIST warning message CDATA #REQUIRED >

<!ELEMENT exec EMPTY >
<!-- one of command or int_cmd must be present -->
<!ATTLIST exec command CDATA #IMPLIED >
<!ATTLIST exec int_cmd (stop_now|stop_gracefully|stop_call) "stop_call" >
<!ATTLIST exec play_pcap CDATA #IMPLIED >
<!ATTLIST exec play_pcap_audio CDATA #IMPLIED >
<!ATTLIST exec rtp_stream CDATA #IMPLIED >
<!ATTLIST exec rtp_echo CDATA #IMPLIED >

<!ELEMENT rtp_echo EMPTY >
<!ATTLIST rtp_echo value CDATA #REQUIRED >

<!ELEMENT strcmp EMPTY >
<!ATTLIST strcmp assign_to CDATA #REQUIRED >
<!ATTLIST strcmp value CDATA #REQUIRED >
<!ATTLIST strcmp variable CDATA #REQUIRED >

<!ELEMENT test EMPTY >
<!ATTLIST test assign_to CDATA #REQUIRED >
<!ATTLIST test compare CDATA #REQUIRED >
<!ATTLIST test value CDATA #REQUIRED >
<!ATTLIST test variable CDATA #REQUIRED >

<!ELEMENT add EMPTY >
<!ATTLIST add assign_to CDATA #REQUIRED >
<!ATTLIST add variable CDATA #REQUIRED >

<!ELEMENT subtract EMPTY >
<!ATTLIST subtract assign_to CDATA #REQUIRED >
<!ATTLIST subtract variable CDATA #REQUIRED >

<!ELEMENT multiply EMPTY >
<!ATTLIST multiply assign_to CDATA #REQUIRED >
<!ATTLIST multiply variable CDATA #REQUIRED >

<!ELEMENT divide EMPTY >
<!ATTLIST divide assign_to CDATA #REQUIRED >
<!ATTLIST divide variable CDATA #REQUIRED >

<!ELEMENT assign EMPTY >
<!ATTLIST assign assign_to CDATA #REQUIRED >
<!ATTLIST assign variable CDATA #REQUIRED >

<!ELEMENT assignstr EMPTY >
<!ATTLIST assignstr assign_to CDATA #REQUIRED >
<!ATTLIST assignstr variable CDATA #REQUIRED >

<!ELEMENT gettimeofday EMPTY >
<!ATTLIST gettimeofday assign_to CDATA #REQUIRED >

<!ELEMENT insert EMPTY >
<!ATTLIST insert file CDATA #REQUIRED >
<!ATTLIST insert value CDATA #REQUIRED >

<!ELEMENT jump EMPTY >
<!ATTLIST jump value CDATA #IMPLIED >
<!ATTLIST jump variable CDATA #IMPLIED >

<!ELEMENT lookup EMPTY >
<!ATTLIST lookup assign_to CDATA #REQUIRED >
<!ATTLIST lookup file CDATA #REQUIRED >
<!ATTLIST lookup key CDATA #REQUIRED >

<!ELEMENT replace EMPTY >
<!ATTLIST replace file CDATA #REQUIRED >
<!ATTLIST replace line CDATA #REQUIRED >
<!ATTLIST replace value CDATA #REQUIRED >

<!ELEMENT sample EMPTY >
<!ATTLIST sample assign_to CDATA #REQUIRED >
<!ATTLIST sample distribution CDATA #REQUIRED >
<!ATTLIST sample mean CDATA #REQUIRED >
<!ATTLIST sample stdev CDATA #REQUIRED >

<!ELEMENT setdest EMPTY >
<!ATTLIST setdest host CDATA #REQUIRED >
<!ATTLIST setdest port CDATA #REQUIRED >
<!ATTLIST setdest protocol CDATA #REQUIRED >

<!ELEMENT todouble EMPTY >
<!ATTLIST todouble assign_to CDATA #REQUIRED >
<!ATTLIST todouble variable CDATA #REQUIRED >

<!ELEMENT urldecode EMPTY >
<!ATTLIST urldecode variable CDATA #REQUIRED >

<!ELEMENT urlencode EMPTY >
<!ATTLIST urlencode variable CDATA #REQUIRED >

<!ELEMENT verifyauth EMPTY >
<!ATTLIST verifyauth assign_to CDATA #REQUIRED >
<!ATTLIST verifyauth username CDATA #REQUIRED >
<!ATTLIST verifyauth password CDATA #REQUIRED >

<!-- END actions -->

<!ELEMENT timewait EMPTY >
<!ATTLIST timewait milliseconds CDATA #REQUIRED >

<!ELEMENT Reference EMPTY >
<!ATTLIST Reference variables CDATA #REQUIRED >

=== IgorrG/testsuite/tests/channels/pjsip/publish/dialog_info_xml/sipp/publish.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="PUBLISH">
  <recv request="PUBLISH" crlf="true">
    <action>
      <ereg regexp="&lt;\?xml version=\"1.0\" encoding=\"UTF-8\"\?&gt;
&lt;dialog-info xmlns=\"urn:ietf:params:xml:ns:dialog-info\" version=\"0\" state=\"full\" entity=\"sip:presence@127.0.0.1:5061\"&gt;
 &lt;dialog id=\"presence\"&gt;
  &lt;state&gt;terminated&lt;/state&gt;
 &lt;/dialog&gt;
&lt;/dialog-info&gt;" check_it="true" search_in="body" assign_to="presence1" />
    </action>
  </recv>

  <Reference variables="presence1" />

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
  </send>

  <recv request="PUBLISH" crlf="true">
    <action>
      <ereg regexp="&lt;\?xml version=\"1.0\" encoding=\"UTF-8\"\?&gt;
&lt;dialog-info xmlns=\"urn:ietf:params:xml:ns:dialog-info\" version=\"1\" state=\"full\" entity=\"sip:presence@127.0.0.1:5061\"&gt;
 &lt;dialog id=\"presence\" direction=\"recipient\"&gt;
  &lt;state&gt;early&lt;/state&gt;
 &lt;/dialog&gt;
&lt;/dialog-info&gt;" check_it="true" search_in="body" assign_to="presence2" />
    </action>
  </recv>

  <Reference variables="presence2" />

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
  </send>

  <recv request="PUBLISH" crlf="true">
    <action>
      <ereg regexp="&lt;\?xml version=\"1.0\" encoding=\"UTF-8\"\?&gt;
&lt;dialog-info xmlns=\"urn:ietf:params:xml:ns:dialog-info\" version=\"2\" state=\"full\" entity=\"sip:presence@127.0.0.1:5061\"&gt;
 &lt;dialog id=\"presence\"&gt;
  &lt;state&gt;confirmed&lt;/state&gt;
 &lt;/dialog&gt;
&lt;/dialog-info&gt;" check_it="true" search_in="body" assign_to="presence3" />
    </action>
  </recv>

  <Reference variables="presence3" />

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
  </send>

  <recv request="PUBLISH" crlf="true">
    <action>
      <ereg regexp="&lt;\?xml version=\"1.0\" encoding=\"UTF-8\"\?&gt;
&lt;dialog-info xmlns=\"urn:ietf:params:xml:ns:dialog-info\" version=\"3\" state=\"full\" entity=\"sip:presence@127.0.0.1:5061\"&gt;
 &lt;dialog id=\"presence\"&gt;
  &lt;state&gt;confirmed&lt;/state&gt;
  &lt;local&gt;
   &lt;target uri=\"sip:presence@127.0.0.1:5061\"&gt;
    &lt;param pname=\"\+sip.rendering\" pvalue=\"no\" /&gt;
   &lt;/target&gt;
  &lt;/local&gt;
 &lt;/dialog&gt;
&lt;/dialog-info&gt;" check_it="true" search_in="body" assign_to="presence4" />
    </action>
  </recv>

  <Reference variables="presence4" />

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
  </send>

  <recv request="PUBLISH" crlf="true">
    <action>
      <ereg regexp="&lt;\?xml version=\"1.0\" encoding=\"UTF-8\"\?&gt;
&lt;dialog-info xmlns=\"urn:ietf:params:xml:ns:dialog-info\" version=\"4\" state=\"full\" entity=\"sip:presence@127.0.0.1:5061\"&gt;
 &lt;dialog id=\"presence\"&gt;
  &lt;state&gt;terminated&lt;/state&gt;
 &lt;/dialog&gt;
&lt;/dialog-info&gt;" check_it="true" search_in="body" assign_to="presence5" />
    </action>
  </recv>

  <Reference variables="presence5" />

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
  </send>

</scenario>

=== IgorrG/testsuite/tests/fax/pjsip/t38_enabled_two_reinvite_on_a_leg/sipp/B_PARTY.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="T38 REINVITE">

<recv request="INVITE" crlf="true"  rrs="true">

<action>
  <ereg regexp="[[:punct:]](.*)[[:punct:]]" search_in="hdr" header="Contact:" check_it="true" assign_to="6,1" />
  <ereg regexp=".*" search_in="hdr" header="From:" check_it="true" assign_to="2" />
  <ereg regexp=".*" search_in="hdr" header="To:" check_it="true" assign_to="3" />
  <log message="Log to avoid the problem of not using $3 [$3]"/>
  <log message="Log to avoid the problem of not using $1 [$1]"/>
  <log message="Log to avoid the problem of not using $2 [$2]"/>
  <log message="Log to avoid the problem of not using $6 [$6]"/>
</action>
</recv>


<send>
<![CDATA[

SIP/2.0 100 Trying
[last_Via:]
[last_Call-ID:]
[last_From:]
[last_To:]
[last_CSeq:]
Content-Length: 0

]]>
</send>

<send retrans="500">
<![CDATA[

SIP/2.0 200 OK
[last_Via:]
[last_Call-ID:]
[last_From:]
[last_To:];tag=[call_number]
[last_CSeq:]
[last_Record-Route]
Contact: <sip:bansallaptop@[local_ip]:[local_port];user=phone>
Content-Type: application/sdp
Content-Length: [len]

v=0
o=HuaweiSoftX3000 6644052 6644052 IN IP[local_ip_type] [local_ip]
s=Sip Call
c=IN IP[media_ip_type] [media_ip]
t=0 0
m=audio 8000 RTP/AVP 0 100 101
a=rtpmap:0 PCMU/8000
a=rtpmap:100 NSE/8000
a=rtpmap:101 telephone-event/101

]]>
</send>

<recv request="ACK"
      rtd="true"
      crlf="true">
</recv>

<pause milliseconds="500" />

<!-- play the pcap now as packets will get through before the reinvite
     After the reinvite B leg sending fails because sipp changes destination port to suit the reinvite port which is incorrect
     for the original call that was negotiated
     After the reinvite the packets get destination port unreachable.
     All the A leg packets get through because asterisk behave correctly
     -->
<nop>
  <action>
    <exec play_pcap_audio="./tests/fax/pjsip/t38_enabled_two_reinvite_on_a_leg/sipp/CUSTOMER_G711U.pcap"/>
  </action>
</nop>

<recv request="INVITE" crlf="true"  rrs="true">
</recv>

<pause milliseconds="200" />

<send retrans="500">
<![CDATA[

SIP/2.0 488 Not Acceptable Here
[last_Via:]
[last_To:]
[last_From:]
[last_Call-ID:]
[last_Cseq:] 
Contact: <sip:390415094280@[local_ip]:[local_port]>
User-Agent: Cisco-SIPGateway/IOS-12.x
Max-Forwards: 69
Content-Length: 0

]]>
</send>

<recv request="ACK"
      rtd="true"
      crlf="true">
</recv>

<recv request="BYE">
</recv>

<send>
<![CDATA[

SIP/2.0 200 OK
[last_Via:]
[last_From:]
[last_To:]
[last_Call-ID:]
[last_CSeq:]
Contact: <sip:[local_ip]:[local_port];transport=[transport]>
Content-Length: 0

    ]]>
</send>

<!-- Keep the call open for a while in case the 200 is lost to be     -->
<!-- able to retransmit it if we receive the BYE again.               -->
<pause milliseconds="4000"/>


<!-- definition of the response time repartition table (unit is ms)   -->
<ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>

<!-- definition of the call length repartition table (unit is ms)     -->
<CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>

=== IgorrG/testsuite/tests/channels/pjsip/auth/uac/multiple_realm_multiple_digest/sipp/multiple_realm_multiple_digest_options.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- If you have a smart XML editor, using the sipp dtd can be a big help -->
<!DOCTYPE scenario SYSTEM "../../../../../../../contrib/sipp/sipp.dtd">
<scenario name="single_realm_single_digest_options">

	<recv request="OPTIONS">
	</recv>

	<!--
		The nonce and opaque have no meaning other than they're properly formatted.
		We're going to send a multiple challenges with the "star" realm and "md5",
		"sha256" and "sha256-512" digest algorithms.  At the time this test was
		written, only "md5" responses should be received from asterisk.
	-->
	<send>
    <![CDATA[

      SIP/2.0 401 Authorization Required
      [last_Via:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0
      WWW-Authenticate: Digest realm="ast",nonce="1618496418/76de4d6a2e8750da189999715d6d55b1",opaque="4982d4386a93d85d",algorithm=sha256,qop="auth"
      WWW-Authenticate: Digest realm="star",nonce="1618496418/76de4d6a2e8750da189999715d6d55b1",opaque="4982d4386a93d85d",algorithm=sha256-512,qop="auth"
      WWW-Authenticate: Digest realm="ast",nonce="1618496418/76de4d6a2e8750da189999715d6d55b1",opaque="4982d4386a93d85d",algorithm=md5,qop="auth"
      WWW-Authenticate: Digest realm="star",nonce="1618496418/76de4d6a2e8750da189999715d6d55b1",opaque="4982d4386a93d85d",algorithm=sha256,qop="auth"
      WWW-Authenticate: Digest realm="ast",nonce="1618496418/76de4d6a2e8750da189999715d6d55b1",opaque="4982d4386a93d85d",algorithm=sha256-512,qop="auth"
      WWW-Authenticate: Digest realm="star",nonce="1618496418/76de4d6a2e8750da189999715d6d55b1",opaque="4982d4386a93d85d",algorithm=md5,qop="auth"

    ]]>
	</send>

	<!--
		sipp has issues with multiple headers with the same name.  If you don't specify
		occurrence, it checks the first header it finds so both eregs below would be
		matched against the first Authorization header.  To get around this, we
		have to specify which header occurrence we want to test. Since Asterisk will
		add Authorization headers in the same order as the WWW-Authenticate headers
		it received, occurrence 1 has to match the first md5 header (ast) and occurrence
		2 has to match the second (star).
	-->
	<recv request="OPTIONS">
		<action>
			<!-- Look for an "ast" realm -->
			<ereg regexp="Digest .*username=.(astuser)..*realm=.(ast)."
				search_in="hdr" header="Authorization:" occurence="1"
				assign_to="junk,username_ast,realm_ast"/>

			<log message="ast: [$username_ast]"/>

			<!-- Look for a "star" realm -->
			<ereg regexp="Digest .*username=.(staruser)..*realm=.(star)."
				search_in="hdr" header="Authorization:"  occurence="2"
				assign_to="junk,username_star,realm_star"/>

			<log message="star: [$username_star]"/>

		</action>
	</recv>

	<!--
		One of the realms has to pass.
	-->
	<nop test="username_star" next="goodauth"/>
	<nop test="username_ast" next="goodauth"/>

	<!--
		We're not testing Asterisk's ability to handle repeated auth failures
		so we just send back a 503 and terminate the test with prejudice
	-->
	<send>
    <![CDATA[

      SIP/2.0 503 Service Unavailable
      [last_Via:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
	</send>

	<nop>
		<action>
			<!--
				Terminate the test with prejudice.
				sipp will return a non-zero return code which
				will cause the test to fail.
			-->
			<exec int_cmd="stop_now"/>
		</action>
	</nop>

	<!-- Auth passed so just send back an OK and we're done -->
	<label id="goodauth"/>

	<send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: [len]

    ]]>
	</send>

	<Reference variables="junk,username_ast,username_star,realm_ast,realm_star"/>
</scenario>

=== IgorrG/testsuite/tests/channels/pjsip/rel100/outgoing/peer_supported_used/sipp/check_100rel.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="Testing 100rel support and usage when required by callee">
  <recv request="INVITE" rtd="true" crlf="true">
      <!-- Save the from tag. We'll need it when we send our BYE -->
      <action>
          <ereg regexp=".*(;tag=.*)"
              header="From:"
              search_in="hdr"
              check_it="true"
              assign_to="remote_tag"/>
          <ereg regexp="100rel"
              header="Supported:"
              search_in="hdr"
              check_it="true"
              assign_to="1"/>
      </action>
  </recv>
  
  <send>
    <![CDATA[

      SIP/2.0 183 Call progress
      [last_Via:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[service]@[local_ip]:[local_port];transport=[transport]>
      Require: 100rel
      RSeq: 3000
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 100 100 IN IP[local_ip_type] 127.0.0.2
      s=-
      c=IN IP[media_ip_type] 127.0.0.2
      t=0 0
      m=audio [media_port] RTP/AVP 0
      a=rtpmap:0 PCMU/8000

    ]]>
    <action>
      <assignstr assign_to="invite_via" value="[last_Via:]" />
      <assignstr assign_to="invite_from" value="[last_From:]" />
      <assignstr assign_to="invite_to" value="[last_To:]" />
      <assignstr assign_to="invite_cseq" value="[last_CSeq:]" />
    </action>
  </send>

  <recv request="PRACK" rtd="true" crlf="true">
      <!-- Save the from tag. We'll need it when we send our BYE -->
      <action>
          <ereg regexp="3000 ([0-9]{1,5}) INVITE"
              header="RAck: "
              search_in="hdr"
              check_it="true"
              assign_to="1"/>
      </action>
  </recv>

  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[service]@[local_ip]:[local_port];transport=[transport]>

    ]]>
  </send>

  <pause/>

  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      [$invite_via]
      [$invite_from]
      [$invite_to];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [$invite_cseq]
      Contact: <sip:[service]@[local_ip]:[local_port];transport=[transport]>
      Supported: 100rel
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 5 5 IN IP[local_ip_type] 127.0.0.3
      s=-
      c=IN IP[media_ip_type] 127.0.0.3
      t=0 0
      m=audio [media_port] RTP/AVP 0
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv request="ACK"
        rtd="true"
        crlf="true">
  </recv>

  <send retrans="500">
    <![CDATA[

      BYE sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: sipp <sip:sipp@[local_ip]:[local_port]>;tag=[pid]SIPpTag01[call_number]
      To: [$remote_tag]
      [last_Call-ID:]
      CSeq: [cseq] BYE
      Contact: sip:sipp@[local_ip]:[local_port]
      Max-Forwards: 70
      Subject: Performance Test
      Content-Length: 0

    ]]>
  </send>

  <recv response="200" />

  <Reference variables="remote_tag,invite_via,invite_from,invite_to,invite_cseq,1" />

</scenario>

=== IgorrG/testsuite/tests/apps/queues/transfer/caller_blind/sipp/wait-for-a-call-then-send-bye.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="UAS 100 responder">

  <recv request="INVITE" crlf="true">
      <!-- Save the from tag. We'll need it when we send our BYE -->
      <action>
          <ereg regexp="(;tag=.*)"
              header="From:"
              search_in="hdr"
              check_it="true"
              assign_to="remote_tag"/>
	  </action>
  </recv>

  <send>
    <![CDATA[

      SIP/2.0 100 Trying
      [last_Via:]
      [last_From:]
      [last_To:];tag=[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
  </send>

  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [media_port] RTP/AVP 0
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv request="ACK"
        crlf="true">
  </recv>

  <pause milliseconds="1000" />

  <send retrans="500">
    <![CDATA[

      BYE sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      [last_Via:]
      [last_From:]
      To: [$remote_tag]
      [last_Call-ID:]
      CSeq: 2 BYE
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Max-Forwards: 70
      Content-Length: 0

    ]]>
  </send>

  <recv response="200">
  </recv>

  <!-- Keep the call open for a while in case the 200 is lost to be     -->
  <!-- able to retransmit it if we receive the BYE again.               -->
  <pause milliseconds="500"/>

  <!-- definition of the response time repartition table (unit is ms)   -->
  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>

  <!-- definition of the call length repartition table (unit is ms)     -->
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>

=== IgorrG/testsuite/tests/fax/pjsip/t38_enabled_two_reinvite_on_a_leg/sipp/A_PARTY.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="T38 REINVTE">
<send retrans="500">
<![CDATA[

INVITE sip:[service]@[remote_ip]:[remote_port] SIP/2.0
Via: SIP/2.0/UDP [local_ip]:[local_port];branch=[branch]
From: <sip:390415094280@[local_ip]:[local_port]>;tag=[pid]SIPpTag00[call_number]
To: <sip:[service]@[remote_ip]:[remote_port]>
Call-ID: [call_id]
X-VCC-UUID: [pid][clock_tick][call_number]
X-VCC-Provider: 61 [local_ip] BEL
Supported: rel1xx,timer,replaces
Min-SE:  181
User-Agent: Cisco-SIPGateway/IOS-12.x
Allow: INVITE, OPTIONS, BYE, CANCEL, ACK, PRACK, COMET, REFER, SUBSCRIBE, NOTIFY, INFO, UPDATE, REGISTER
CSeq: 101 INVITE
Max-Forwards: 69
Contact: <sip:390415094280@[local_ip]:[local_port]>
Expires: 180
Allow-Events: telephone-event
Content-Type: application/sdp
Content-Length: [len]
      
v=0
o=CiscoSystemsSIP-GW-UserAgent 9624 5279 IN IP4 [local_ip]
s=SIP Call
c=IN IP4 [media_ip]
t=0 0
m=audio 9000 RTP/AVP 0 18 101
c=IN IP[local_ip_type] [local_ip]
a=rtpmap:101 telephone-event/101

]]>
</send>

<recv response="100">
</recv>

<recv response="100" optional="true">
</recv>

<recv response="100" optional="true">
</recv>

<recv response="180" optional="true">
</recv>
<recv response="183" optional="true">
</recv>

<recv response="200" rrs="true">
   <action>
  	<ereg regexp="[[:punct:]](.*)[[:punct:]]" search_in="hdr" header="Contact:" check_it="true" assign_to="6,1" />
    	<ereg regexp=".*" search_in="hdr" header="From:" check_it="true" assign_to="2" />
    	<ereg regexp=".*" search_in="hdr" header="To:" check_it="true" assign_to="3" />
    	<log message="Log to avoid the problem of not using $6 [$6]"/>
   </action>
</recv>

<send>
<![CDATA[

ACK [next_url] SIP/2.0
[routes]
Via: SIP/2.0/UDP [local_ip]:[local_port];branch=[branch]
From: [$2]
To: [$3]
Call-ID: [call_id]
Max-Forwards: 69
CSeq: 101 ACK
Content-Length: [len]

]]>
</send>


<pause milliseconds="2000"/>

<send retrans="500">

<![CDATA[

INVITE [$1] SIP/2.0
Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
From: [$2]
To: [$3]
Call-ID: [call_id]
CSeq: 102 INVITE
Contact: <sip:[local_ip]:[local_port]>
Max-Forwards: 70
Content-Type: application/sdp
[routes]
Allow-Events: telephone-event
Content-Length: [len] 

v=0
o=CiscoSystemsSIP-GW-UserAgent 9624 5280 IN IP4 [local_ip]
s=Asterisk PBX 1.6.2.0
c=IN IP[local_ip_type] [local_ip]
t=0 0
m=image 4389 udptl t38
a=T38FaxVersion:0
a=T38MaxBitRate:14400
a=T38FaxRateManagement:transferredTCF
a=T38FaxMaxDatagram:1400
a=T38FaxUdpEC:t38UDPRedundancy

]]>

</send>

<recv response="100" optional="true">
</recv>
  
<recv response="488" rrs="true">
</recv>


<send>
<![CDATA[

ACK [$1] SIP/2.0
Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
[last_Call-ID:]
[last_From]
[last_To]
CSeq: 102 ACK
Max-Forwards: 70
[routes]
Content-Length: 0


]]>
</send>

<pause milliseconds="2000"/>

<send retrans="500">

<![CDATA[

INVITE [$1] SIP/2.0
Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
[last_Call-ID:]
From: [$2]
To: [$3]
CSeq: 103 INVITE
Contact: <sip:[local_ip]:[local_port]>
Max-Forwards: 70
Content-Type: application/sdp
[routes]
Allow-Events: telephone-event
Content-Length: [len] 

v=0
o=HuaweiSoftX3000 6644052 6644052 IN IP[local_ip_type] [local_ip]
s=Sip Call
c=IN IP[media_ip_type] [media_ip]
t=0 0
m=audio 9000 RTP/AVP 0 18 101
c=IN IP[local_ip_type] [local_ip]
a=rtpmap:101 telephone-event/101


]]>

</send>

<recv response="100" optional="true">
</recv>
  
<recv response="200" rrs="true">
</recv>

<send>
<![CDATA[

ACK [$1] SIP/2.0
Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
[last_Call-ID:]
[last_From]
[last_To]
CSeq: 103 ACK
Max-Forwards: 70
[routes]
Content-Length: 0


]]>

</send>

<pause milliseconds="2000" />

<nop>
  <action>
    <exec play_pcap_audio="./tests/fax/pjsip/t38_enabled_two_reinvite_on_a_leg/sipp/CARRIER_G711U.pcap"/>
  </action>
</nop>

<pause milliseconds="20000" />
  
<send retrans="500">
<![CDATA[

BYE [$1] SIP/2.0
Via: SIP/2.0/UDP [local_ip]:[local_port];branch=[branch]
To: [$3]
From: [$2]
[last_Call-ID:]
User-Agent: Cisco-SIPGateway/IOS-12.x
Max-Forwards: 69
CSeq: 104 BYE
Content-Length: 0

]]>
</send>

<recv response="200">
</recv>


</scenario>
