=== IgorrG/testsuite/contrib/sipp/sipp.dtd
<!ELEMENT scenario ( CallLengthRepartition | ResponseTimeRepartition | Reference | send | recv | pause | nop | sendCmd | recvCmd | label | timewait)* >
<!ATTLIST scenario name CDATA #IMPLIED >

<!-- BEGIN message commands -->

<!ENTITY % messageCmdCommon '
  start_rtd NMTOKEN #IMPLIED
  rtd NMTOKEN #IMPLIED
  repeat_rtd (true|false) #IMPLIED
  crlf (true|false) #IMPLIED
  next NMTOKEN #IMPLIED
  test NMTOKEN #IMPLIED
  chance NMTOKEN #IMPLIED
  condexec NMTOKEN #IMPLIED
  condexec_inverse NMTOKEN #IMPLIED
  counter NMTOKEN #IMPLIED
  '>

<!ELEMENT send (#PCDATA|action)* >
<!ATTLIST send %messageCmdCommon; >
<!ATTLIST send retrans NMTOKEN #IMPLIED >
<!ATTLIST send lost NMTOKEN #IMPLIED >
<!ATTLIST send start_txn NMTOKEN #IMPLIED >
<!ATTLIST send ack_txn NMTOKEN #IMPLIED >

<!ELEMENT recv ( action? ) >
<!ATTLIST recv %messageCmdCommon; >
<!ATTLIST recv response NMTOKEN #IMPLIED >
<!ATTLIST recv request CDATA #IMPLIED >
<!ATTLIST recv optional (true|false) #IMPLIED >
<!ATTLIST recv ignosesdp (true|false) #IMPLIED >
<!ATTLIST recv rrs (true|false) #IMPLIED >
<!ATTLIST recv auth (true|false) #IMPLIED >
<!ATTLIST recv lost NMTOKEN #IMPLIED >
<!ATTLIST recv timeout NMTOKEN #IMPLIED >
<!ATTLIST recv ontimeout NMTOKEN #IMPLIED >
<!ATTLIST recv regexp_match (true|false) #IMPLIED >
<!ATTLIST recv response_txn NMTOKEN #IMPLIED >

<!ELEMENT pause EMPTY >
<!ATTLIST pause %messageCmdCommon; >
<!ATTLIST pause milliseconds NMTOKEN #IMPLIED >
<!ATTLIST pause variable NMTOKEN #IMPLIED >
<!ATTLIST pause distribution NMTOKEN #IMPLIED >
<!ATTLIST pause sanity_check (true|false) #IMPLIED >

<!ELEMENT nop ( action? ) >
<!ATTLIST nop %messageCmdCommon; >
<!ATTLIST nop display CDATA #IMPLIED >

<!ELEMENT sendCmd ( #PCDATA ) >
<!ATTLIST sendCmd %messageCmdCommon; >
<!ATTLIST sendCmd dest NMTOKEN #IMPLIED >

<!ELEMENT recvCmd ( action? ) >
<!ATTLIST recvCmd %messageCmdCommon; >
<!ATTLIST recvCmd src NMTOKEN #IMPLIED >

<!-- END message commands -->

<!ELEMENT label ( #PCDATA ) >
<!ATTLIST label id NMTOKEN #IMPLIED >

<!ELEMENT ResponseTimeRepartition EMPTY >
<!ATTLIST ResponseTimeRepartition value CDATA #REQUIRED >

<!ELEMENT CallLengthRepartition EMPTY >
<!ATTLIST CallLengthRepartition value CDATA #REQUIRED >

<!ELEMENT action ( add | assign | assignstr | divide | ereg | exec | gettimeofday | insert | jump | log | lookup | multiply | replace | rtp_echo | sample | setdest | strcmp | subtract | test | todouble | urldecode | urlencode | verifyauth | warning )+ >

<!-- BEGIN actions -->

<!ELEMENT ereg EMPTY >
<!ATTLIST ereg assign_to CDATA #REQUIRED >
<!ATTLIST ereg case_indep (true|false) #IMPLIED >
<!ATTLIST ereg check_it (true|false) "false" >
<!ATTLIST ereg check_it_inverse (true|false) "false" >
<!ATTLIST ereg header NMTOKEN #IMPLIED >
<!ATTLIST ereg occurence CDATA #IMPLIED >
<!ATTLIST ereg regexp CDATA #REQUIRED >
<!ATTLIST ereg search_in (msg|hdr) "msg" >
<!ATTLIST ereg start_line (true|false) #IMPLIED >
<!ATTLIST ereg variable CDATA #IMPLIED >


<!ELEMENT log EMPTY >
<!ATTLIST log message CDATA #REQUIRED >

<!ELEMENT warning EMPTY >
<!ATTLIST warning message CDATA #REQUIRED >

<!ELEMENT exec EMPTY >
<!-- one of command or int_cmd must be present -->
<!ATTLIST exec command CDATA #IMPLIED >
<!ATTLIST exec int_cmd (stop_now|stop_gracefully|stop_call) "stop_call" >
<!ATTLIST exec play_pcap CDATA #IMPLIED >
<!ATTLIST exec play_pcap_audio CDATA #IMPLIED >
<!ATTLIST exec rtp_stream CDATA #IMPLIED >
<!ATTLIST exec rtp_echo CDATA #IMPLIED >

<!ELEMENT rtp_echo EMPTY >
<!ATTLIST rtp_echo value CDATA #REQUIRED >

<!ELEMENT strcmp EMPTY >
<!ATTLIST strcmp assign_to CDATA #REQUIRED >
<!ATTLIST strcmp value CDATA #REQUIRED >
<!ATTLIST strcmp variable CDATA #REQUIRED >

<!ELEMENT test EMPTY >
<!ATTLIST test assign_to CDATA #REQUIRED >
<!ATTLIST test compare CDATA #REQUIRED >
<!ATTLIST test value CDATA #REQUIRED >
<!ATTLIST test variable CDATA #REQUIRED >

<!ELEMENT add EMPTY >
<!ATTLIST add assign_to CDATA #REQUIRED >
<!ATTLIST add variable CDATA #REQUIRED >

<!ELEMENT subtract EMPTY >
<!ATTLIST subtract assign_to CDATA #REQUIRED >
<!ATTLIST subtract variable CDATA #REQUIRED >

<!ELEMENT multiply EMPTY >
<!ATTLIST multiply assign_to CDATA #REQUIRED >
<!ATTLIST multiply variable CDATA #REQUIRED >

<!ELEMENT divide EMPTY >
<!ATTLIST divide assign_to CDATA #REQUIRED >
<!ATTLIST divide variable CDATA #REQUIRED >

<!ELEMENT assign EMPTY >
<!ATTLIST assign assign_to CDATA #REQUIRED >
<!ATTLIST assign variable CDATA #REQUIRED >

<!ELEMENT assignstr EMPTY >
<!ATTLIST assignstr assign_to CDATA #REQUIRED >
<!ATTLIST assignstr variable CDATA #REQUIRED >

<!ELEMENT gettimeofday EMPTY >
<!ATTLIST gettimeofday assign_to CDATA #REQUIRED >

<!ELEMENT insert EMPTY >
<!ATTLIST insert file CDATA #REQUIRED >
<!ATTLIST insert value CDATA #REQUIRED >

<!ELEMENT jump EMPTY >
<!ATTLIST jump value CDATA #IMPLIED >
<!ATTLIST jump variable CDATA #IMPLIED >

<!ELEMENT lookup EMPTY >
<!ATTLIST lookup assign_to CDATA #REQUIRED >
<!ATTLIST lookup file CDATA #REQUIRED >
<!ATTLIST lookup key CDATA #REQUIRED >

<!ELEMENT replace EMPTY >
<!ATTLIST replace file CDATA #REQUIRED >
<!ATTLIST replace line CDATA #REQUIRED >
<!ATTLIST replace value CDATA #REQUIRED >

<!ELEMENT sample EMPTY >
<!ATTLIST sample assign_to CDATA #REQUIRED >
<!ATTLIST sample distribution CDATA #REQUIRED >
<!ATTLIST sample mean CDATA #REQUIRED >
<!ATTLIST sample stdev CDATA #REQUIRED >

<!ELEMENT setdest EMPTY >
<!ATTLIST setdest host CDATA #REQUIRED >
<!ATTLIST setdest port CDATA #REQUIRED >
<!ATTLIST setdest protocol CDATA #REQUIRED >

<!ELEMENT todouble EMPTY >
<!ATTLIST todouble assign_to CDATA #REQUIRED >
<!ATTLIST todouble variable CDATA #REQUIRED >

<!ELEMENT urldecode EMPTY >
<!ATTLIST urldecode variable CDATA #REQUIRED >

<!ELEMENT urlencode EMPTY >
<!ATTLIST urlencode variable CDATA #REQUIRED >

<!ELEMENT verifyauth EMPTY >
<!ATTLIST verifyauth assign_to CDATA #REQUIRED >
<!ATTLIST verifyauth username CDATA #REQUIRED >
<!ATTLIST verifyauth password CDATA #REQUIRED >

<!-- END actions -->

<!ELEMENT timewait EMPTY >
<!ATTLIST timewait milliseconds CDATA #REQUIRED >

<!ELEMENT Reference EMPTY >
<!ATTLIST Reference variables CDATA #REQUIRED >

=== IgorrG/testsuite/tests/channels/pjsip/non_negotiated_frame_SSRC_change/sipp/uas_asterisk.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="Re-Invite problem 1">

<recv request="INVITE" crlf="true" rrs="true">
</recv>



<send>
<![CDATA[

SIP/2.0 100 Trying
[last_Via:]
[last_Call-ID:]
[last_From:]
[last_To:]
[last_CSeq:]
Content-Length: 0

]]>
</send>

<send retrans="500">
<![CDATA[

SIP/2.0 200 OK
[last_Via:]
[last_Call-ID:]
[last_From:]
[last_To:];tag=[call_number]
[last_CSeq:]
[last_Record-Route]
Contact: <sip:bansallaptop@[local_ip]:[local_port];user=phone>
Content-Type: application/sdp
Content-Length: [len]

v=0
o=HuaweiSoftX3000 6644052 6644052 IN IP[local_ip_type] [local_ip]
s=Sip Call
c=IN IP4 127.0.0.1
t=0 0
m=audio 9000 RTP/AVP 8 103
a=rtpmap:8 PCMA/8000
a=rtpmap:103 telephone-event/8000

]]>
</send>

<recv request="ACK"
      rtd="true"
      crlf="true">
</recv>

<pause milliseconds="40"/>

  <nop>
    <action>
	    <exec play_pcap_audio="tests/channels/pjsip/non_negotiated_frame_SSRC_change/sipp/g711a.pcap"/>
    </action>
  </nop>
  <recv request="BYE">
  </recv>

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
  </send>



<!-- Keep the call open for a while in case the 200 is lost to be     -->
<!-- able to retransmit it if we receive the BYE again.               -->
<pause milliseconds="4000"/>


<!-- definition of the response time repartition table (unit is ms)   -->
<ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>

<!-- definition of the call length repartition table (unit is ms)     -->
<CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>

=== IgorrG/testsuite/tests/apps/confbridge/sfu_no_video_source/sipp/video_caller_first.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="INVITE to ConfBridge with SDP in initial INVITE">
  <send retrans="500">
    <![CDATA[

      INVITE sip:conference@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: test1 <sip:[service]@[local_ip]:[local_port]>;tag=[call_number]
      To: test <sip:test@[remote_ip]:[remote_port]>
      Call-ID: [call_id]
      CSeq: 1 INVITE
      Contact: <sip:test@[local_ip]:[local_port];transport=[transport]>
      Max-Forwards: 70
      Subject: Test
      User-Agent: Test
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=phoneA 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio 6000 RTP/AVP 0
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv response="100"
        optional="true">
  </recv>

  <recv response="200" rtd="true">
  </recv>

  <send>
    <![CDATA[

      ACK sip:conference@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: test1 <sip:[service]@[local_ip]:[local_port]>;tag=[call_number]
      To: test <sip:test@[remote_ip]:[remote_port]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 1 ACK
      Contact: <sip:test@[local_ip]:[local_port];transport=[transport]>
      Max-Forwards: 70
      Subject: Test
      Content-Length: 0

    ]]>
  </send>

  <recv request="INVITE">
    <action>
      <ereg regexp="m=video [0-9]{1,5} RTP/AVP 99+..*"
            search_in="body" check_it="true" assign_to="1"/>
      <test assign_to="1" variable="1" compare="equal" value=""/>
    </action>
  </recv>

  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:test@[local_ip]:[local_port];transport=[transport]>
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=phoneA 53655765 2353687638 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio 6000 RTP/AVP 0
      a=rtpmap:0 PCMU/8000
      m=video 6002 RTP/AVP 99
      a=rtpmap:99 H264/90000

    ]]>
  </send>

  <recv request="ACK"
        rtd="true"
        crlf="true">
  </recv>

  <recv request="INVITE">
    <action>
      <ereg regexp="m=video 0 RTP/AVP 99+..*"
            search_in="body" check_it="true" assign_to="2"/>
      <test assign_to="2" variable="2" compare="equal" value=""/>
    </action>
  </recv>

  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:test@[local_ip]:[local_port];transport=[transport]>
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=phoneA 53655765 2353687639 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio 6000 RTP/AVP 0
      a=rtpmap:0 PCMU/8000
      m=video 0 RTP/AVP 99

    ]]>
  </send>

  <recv request="ACK"
        rtd="true"
        crlf="true">
  </recv>

  <send retrans="500">
    <![CDATA[

      BYE sip:conference@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: test1 <sip:[service]@[local_ip]:[local_port]>;tag=[call_number]
      To: test <sip:test@[remote_ip]:[remote_port]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: [cseq] BYE
      Contact: <sip:test@[local_ip]:[local_port];transport=[transport]>
      Max-Forwards: 70
      Subject: Test
      Content-Length: 0

    ]]>
  </send>

  <recv response="200">
  </recv>

  <!-- definition of the response time repartition table (unit is ms)   -->
  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>

  <!-- definition of the call length repartition table (unit is ms)     -->
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>

=== IgorrG/testsuite/tests/channels/pjsip/auth/uac/single_realm_single_digest/sipp/single_realm_single_digest_options.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- If you have a smart XML editor, using the sipp dtd can be a big help -->
<!DOCTYPE scenario SYSTEM "../../../../../../../contrib/sipp/sipp.dtd">
<scenario name="single_realm_single_digest_options">

	<recv request="OPTIONS">
	</recv>

	<!--
		The nonce and opaque have no meaning other than they're properly formatted.
		We're going to send a single challenge with the "star" realm and "md5"
		digest algorithm.  99.999% of the cases.
	-->
	<send>
    <![CDATA[

      SIP/2.0 401 Authorization Required
      [last_Via:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0
      WWW-Authenticate: Digest realm="star",nonce="1618496418/76de4d6a2e8750da189999715d6d55b1",opaque="4982d4386a93d85d",algorithm=md5,qop="auth"

    ]]>
	</send>

	<recv request="OPTIONS">
		<action>
			<ereg regexp="Digest .*username=.(.+)..*realm=.(star)."
				search_in="hdr" header="Authorization:"
				assign_to="junk,username,realm"/>
			<!--
				sipp will examine the returned Authentication header and
				validate the username and password.
			-->
			<verifyauth assign_to="authvalid" username="optuser"
				password="optpasswd"/>
		</action>
	</recv>

	<!--
		If authvalid is set, the alidation was successful so skip on
		down to sending an OK.
	-->
	<nop test="authvalid" next="goodauth"/>

	<!--
		We're not testing Asterisk's ability to handle repeated auth failures
		so we just send back a 503 and terminate the test with prejudice
	-->
	<send>
    <![CDATA[

      SIP/2.0 503 Service Unavailable
      [last_Via:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
	</send>

	<nop>
		<action>
			<!--
				Terminate the test with prejudice.
				sipp will return a non-zero return code which
				will cause the test to fail.
			-->
			<exec int_cmd="stop_now"/>
		</action>
	</nop>

	<!-- Auth passed so just send back an OK and we're done -->
	<label id="goodauth"/>

	<send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: [len]

    ]]>
	</send>

	<Reference variables="junk,username,realm"/>
</scenario>

=== IgorrG/testsuite/tests/channels/pjsip/transfers/attended_transfer/nominal/caller_local_direct_media/sipp/wait-for-a-call-then-send-bye.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="UAS 100 responder">

  <recv request="INVITE">

    <action>
      <!-- since we need to send a request to the remote part -->
      <!-- we need to extract the Contact and the From header content -->
      <ereg regexp=".*" search_in="hdr" header="From: " assign_to="remote_from"/>
      <ereg regexp=".*" search_in="hdr" header="To: " assign_to="remote_to"/>
      <!-- assign the content of the Contaact SIP URI to the remote_contact var -->
      <!-- first var of assign_to contains the whole match -->
      <ereg regexp="sip:(.*)>.*" search_in="hdr" header="Contact" assign_to="trash,remote_contact"/>
    </action>

  </recv>

  <!-- since SIPp complains about not used variable reference the trach var -->
  <Reference variables="trash"/>

  <send>
    <![CDATA[

      SIP/2.0 100 Trying
      [last_Via:]
      [last_From:]
      [last_To:];tag=[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
  </send>

  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [media_port] RTP/AVP 0
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv request="ACK"
        crlf="true">
  </recv>

  <!-- Send audio -->
  <nop>
    <action>
      <exec rtp_stream="lib/python/asterisk/audio.ulaw,3,0"/>
    </action>
  </nop>

  <label id="waitagain"/>
  <recv request="INVITE" timeout="5000" ontimeout="sendBYE"/>
  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:alice@[local_ip]:[local_port]>
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [media_port] RTP/AVP 0
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>
  <recv request="ACK" next="waitagain"/>

  <label id="sendBYE"/>
  <send retrans="500">
    <![CDATA[

      BYE sip:[$remote_contact] SIP/2.0
      [last_Via:]
      From: [$remote_to];tag=[call_number]
      To: [$remote_from]
      [last_Call-ID:]
      CSeq: [cseq] BYE
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Max-Forwards: 70
      Content-Length: 0

    ]]>
  </send>

  <recv response="200"/>

  <!-- Keep the call open for a while in case the 200 is lost to be     -->
  <!-- able to retransmit it if we receive the BYE again.               -->
  <pause milliseconds="500"/>

  <label id="scenario_end"/>

  <!-- definition of the response time repartition table (unit is ms)   -->
  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>

  <!-- definition of the call length repartition table (unit is ms)     -->
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>

=== IgorrG/testsuite/tests/rtp/rtp_range/rtp_range_even_odd/sipp/call_accept_test_range.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="INVITE to echo with SDP in initial INVITE">
  <send retrans="500">
    <![CDATA[

      INVITE sip:test@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: test[call_number] <sip:[service]@[local_ip]:[local_port]>;tag=[call_number]
      To: test <sip:test@[remote_ip]:[remote_port]>
      Call-ID: [call_id]
      CSeq: 1 INVITE
      Contact: <sip:test@[local_ip]:[local_port];transport=[transport]>
      Max-Forwards: 70
      Subject: Test
      User-Agent: Test
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=phoneA 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio 6000 RTP/AVP 0
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv response="100"
        optional="true">
  </recv>

  <recv response="488"
        optional="true"
        next="1"
        rtd="true">
        <action>
          <ereg regexp="test[4-6]" search_in="hdr" header="From: " assign_to="4"/>
          <test assign_to="4" variable="4" compare="equal" value=""/>
        </action>
  </recv>

  <recv response="200" rtd="true">
      <action>
      <ereg regexp="m=audio 1000[0-4] RTP/AVP 0+..*"
            search_in="body" check_it="true" assign_to="5"/>
      <test assign_to="5" variable="5" compare="equal" value=""/>
    </action>
  </recv>

  <send>
    <![CDATA[

      ACK sip:test@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: test[call_number] <sip:[service]@[local_ip]:[local_port]>;tag=[call_number]
      To: test <sip:test@[remote_ip]:[remote_port]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 1 ACK
      Contact: <sip:test@[local_ip]:[local_port];transport=[transport]>
      Max-Forwards: 70
      Subject: Test
      Content-Length: 0

    ]]>
  </send>

  <recv request="BYE">
  </recv>

  <send next="2">
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
  </send>

  <label id="1"/>

  <send next="2">
    <![CDATA[

      ACK sip:test@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: test[call_number] <sip:[service]@[local_ip]:[local_port]>;tag=[call_number]
      To: test <sip:test@[remote_ip]:[remote_port]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 1 ACK
      Contact: <sip:test@[local_ip]:[local_port];transport=[transport]>
      Max-Forwards: 70
      Subject: Test
      Content-Length: 0

    ]]>
  </send>

  <label id="2"/>

  <!-- definition of the response time repartition table (unit is ms)   -->
  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>

  <!-- definition of the call length repartition table (unit is ms)     -->
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>

=== IgorrG/testsuite/tests/channels/pjsip/subscriptions/mwi/unsolicited/mailbox_count_changes/sipp/alice-is-notified-1.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="alice-is-notified">

  <recv request="NOTIFY" crlf="true">
    <action>
      <ereg regexp="Messages-Waiting:.*" check_it="true" search_in="body" assign_to="mwi" />
      <ereg regexp="Voice-Message:.*" check_it="true" search_in="body" assign_to="vms" />

      <ereg regexp="yes" search_in="var" variable="mwi" check_it="true" assign_to="trash1"/>
      <ereg regexp="2/0" search_in="var" variable="vms" check_it="true" assign_to="trash2"/>
    </action>
  </recv>

  <Reference variables="trash1,trash2" />

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
  </send>
</scenario>

=== IgorrG/testsuite/tests/channels/pjsip/stir_shaken/stir_shaken_mismatch/sipp/send-invite.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="INVITE with Identity Header">
  <send retrans="500">
    <![CDATA[

      INVITE sip:test@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: test1 <sip:[service]@[local_ip]:[local_port]>;tag=[call_number]
      To: test <sip:test@[remote_ip]:[remote_port]>
      Call-ID: 1234567
      CSeq: 1 INVITE
      Contact: <sip:test@[local_ip]:[local_port];transport=[transport]>
      Max-Forwards: 70
      Identity: eyJhbGciOiJFUzI1NiIsInBwdCI6InNoYWtlbiIsInR5cCI6InBhc3Nwb3J0IiwieDV1IjoiaHR0cDovLzEyNy4wLjAuMTo4MDg4L3B1YmxpY194NTA5X2NlcnQucGVtIn0=.eyJvcmlnIjp7InRuIjoiMTIzNDU2NyJ9LCJhdHRlc3QiOiJDIiwib3JpZ2lkIjoidGVzdHN1aXRlIiwiaWF0IjoxNjE4ODY0NzU4fQ==.MEYCIQDpKNbtqxh04gti5E6FNVaE+8kItvp3yBzegZkCn6/iFgIhALOUhJJjNTyckW7JUwSurfY+3rV3ZwOLi5P8ZawgVCNq;info=<http://127.0.0.1:8088/public_x509_cert.pem>alg=ES256;ppt=shaken
      Subject: Test
      User-Agent: Test
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=phoneA 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio 6000 RTP/AVP 0
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv response="100" optional="true"/>

  <recv response="200" rtd="true"/>

  <send>
    <![CDATA[

      ACK sip:test@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: test1 <sip:[service]@[local_ip]:[local_port]>;tag=[call_number]
      To: test <sip:test@[remote_ip]:[remote_port]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 1 ACK
      Contact: <sip:test@[local_ip]:[local_port];transport=[transport]>
      Max-Forwards: 70
      Subject: Test
      Content-Length: 0

    ]]>
  </send>

  <recv request="BYE"/>

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:test@[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
  </send>

</scenario>

=== IgorrG/testsuite/tests/channels/pjsip/moh_passthru_inactive/sipp/uas_hold_reinvite.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="Re-Invite problem 1">

<recv request="INVITE" crlf="true"  rrs="true">
  <action>
    <ereg regexp="[[:punct:]](.*)[[:punct:]]" search_in="hdr" header="Contact:" check_it="true" assign_to="6,1" />
    <ereg regexp=".*" search_in="hdr" header="From:" check_it="true" assign_to="2" />
    <ereg regexp=".*" search_in="hdr" header="To:" check_it="true" assign_to="3" />
  </action>
</recv>
<Reference variables="9"/>


<send>
<![CDATA[

SIP/2.0 100 Trying
[last_Via:]
[last_Call-ID:]
[last_From:]
[last_To:]
[last_CSeq:]
Content-Length: 0

]]>
</send>

<send retrans="500">
<![CDATA[

SIP/2.0 200 OK
[last_Via:]
[last_Call-ID:]
[last_From:]
[last_To:];tag=[call_number]
[last_CSeq:]
Contact: <sip:736596371553211257@[local_ip]:[local_port];user=phone>
Content-Type: application/sdp
[last_Record-Route]
Content-Length: [len]

v=0
o=HuaweiSoftX3000 6644052 6644052 IN IP[local_ip_type] [local_ip]
s=Sip Call
c=IN IP[media_ip_type] [media_ip]
t=0 0
m=audio [media_port] RTP/AVP 8 0 18 101
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:18 G729/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15

]]>
</send>

<recv request="ACK"
      rtd="true"
      crlf="true">
</recv>

<pause milliseconds="500"/>

<send retrans="500">
<![CDATA[

INVITE [$1] SIP/2.0
Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
[last_Call-ID:]
From: [$3];tag=[call_number]
To: [$2]
CSeq: 1 INVITE
Contact: <sip:[local_ip]:[local_port]>
Max-Forwards: 70
Content-Type: application/sdp
[routes]
Content-Length: [len] 

v=0
o=HuaweiSoftX3000 6644052 6644052 IN IP[local_ip_type] [local_ip]
s=Sip Call
c=IN IP[media_ip_type] 0.0.0.0
t=0 0
m=audio [media_port] RTP/AVP 8 0 18 101
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:18 G729/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendonly

]]>
</send>

<recv response="100" optional="true">
</recv>

<recv response="100" optional="true">
</recv>

<recv response="200" rtd="true" crlf="true">
  <action>
    <ereg regexp="a=recvonly" search_in="body" check_it="true" assign_to="9"/>
  </action>
</recv>
<Reference variables="9"/>


<send>
<![CDATA[

ACK [$1] SIP/2.0
Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
[last_Call-ID:]
From: [$3];tag=[call_number]
To: [$2]
CSeq: 1 ACK
Max-Forwards: 70
Content-Length: 0
[routes]

]]>
</send>

<recv request="INVITE" crlf="true">
  <action>
    <ereg regexp="a=inactive" search_in="body" check_it="true" assign_to="10"/>
  </action>
</recv>
<Reference variables="10"/>

<send retrans="500">
<![CDATA[

SIP/2.0 200 OK
[last_Via:]
[last_From:]
[last_To:];tag=[call_number]
[last_Call-ID:]
[last_CSeq:]
Contact: <sip:[local_ip]:[local_port];transport=[transport]>
[last_Record-Route]
Content-Type: application/sdp
Content-Length: [len]

v=0
o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
s=-
c=IN IP[media_ip_type] [media_ip]
t=0 0
m=audio [media_port] RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=inactive

]]>
</send>

<recv request="ACK" rtd="true" crlf="true">
</recv>

<recv request="INVITE" crlf="true">
  <action>
    <ereg regexp="a=recvonly" search_in="body" check_it="true" assign_to="11"/>
  </action>
</recv>
<Reference variables="11"/>

<send retrans="500">
<![CDATA[

SIP/2.0 200 OK
[last_Via:]
[last_From:]
[last_To:];tag=[call_number]
[last_Call-ID:]
[last_CSeq:]
Contact: <sip:[local_ip]:[local_port];transport=[transport]>
[last_Record-Route]
Content-Type: application/sdp
Content-Length: [len]

v=0
o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
s=-
c=IN IP[media_ip_type] [media_ip]
t=0 0
m=audio [media_port] RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=sendonly

]]>
</send>

<recv request="ACK" rtd="true" crlf="true">
</recv>

<recv request="BYE">
</recv>

<send>
<![CDATA[

SIP/2.0 200 OK
[last_Via:]
[last_From:]
[last_To:]
[last_Call-ID:]
[last_CSeq:]
Content-Length: 0

]]>
</send>


<!-- Keep the call open for a while in case the 200 is lost to be     -->
<!-- able to retransmit it if we receive the BYE again.               -->
<pause milliseconds="4000"/>


</scenario>
